// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	Title      string `json:"title"`
	Author     string `json:"author"`
	DatePub    string `json:"date_pub"`
	BookCvrImg string `json:"book_cvr_img"`
}

type BookInput struct {
	Title      string `json:"title"`
	Author     string `json:"author"`
	DatePub    string `json:"date_pub"`
	BookCvrImg string `json:"book_cvr_img"`
}
